apiVersion: v1
kind: ConfigMap
metadata:
  name: attic-config
  namespace: attic
data:
  server.toml: |
    listen = "[::]:8080"
    api-endpoint = "https://nix.charemma.de/"

    [database]
    url = "sqlite:///data/attic.db?mode=rwc"

    [storage]
    type = "local"
    path = "/data/storage"

    [chunking]
    nar-size-threshold = 65536
    min-size = 16384
    avg-size = 65536
    max-size = 262144

    [compression]
    type = "zstd"

    [garbage-collection]
    interval = "12 hours"
    default-retention-period = "6 months"
