apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airdata-particulate
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/charemma/monorepo
    targetRevision: HEAD
    path: airdata/particulate/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
