apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: zeddl
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: zeddl
      images:
        - alias: app
          imageName: ghcr.io/charemma/zeddl:latest
          commonUpdateSettings:
            updateStrategy: newest-build
          manifestTargets:
            kustomize:
              name: ghcr.io/charemma/zeddl
      writeBackConfig:
        method: git:secret:argocd/charemma-github
        gitConfig:
          repository: https://github.com/charemma/zeddl
          branch: main
          writeBackTarget: "kustomization:."
  writeBackConfig:
    method: argocd
