config:
  nix-builder:provider: aws
  aws:region: eu-central-1
  nix-builder:sshPublicKeyPath: ~/.ssh/id_ed25519.pub
  nix-builder:builders:
    aarch64:
      serverType: c7g.2xlarge
      arch: aarch64-linux
      cores: 8
      diskGb: 120
      count: 1
  # AWS credentials are NOT stored here. Set them encrypted with:
  #   pulumi config set aws:accessKey --secret
  #   pulumi config set aws:secretKey --secret
  # or export AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY in the environment.

  aws:accessKey:
    secure: AAABANrkwTb+qWfR//WafP2MVMTkMgH5fVCzUcrAV7O1tbp5pt4ePsItwUSd9Dd73t8SXw==
  aws:secretKey:
    secure: AAABAOPlbxqvQL4Tofkfsc1kDqe1WqIuV/qsDFd+M5J4qOAxN71GVC78iUqnJN3zs3U2bUtYORpJJXDUuLIWxeeckygBO+NB
  nix-builder:cacheSigningKey:
    secure: AAABADP1d5JgZZjSoQSjQZBvzhZS+8ntJM6oRIYtLQ/16ComXlL8+VWa/qtFsn2hk+ozvFu9LIjVgLpElCvNgRjGQIxvCbmVaLLICrPQRowcKljJAQYIUDH/bP3fBo0vZGzx5en3zKWPCZ4iOgtzKN8wRWyPtmTs8ZW3YgfTzrSFI8WCQMPi2+hGZ+hH
  nix-builder:cachePublicKey: charemma-nix-cache-1:R/svQq6DM5KAHVlkP1w7tXXcH3VhyV5iJFu+7OV/c6U=
  nix-builder:cacheBucket: charemma-nix-cache
