config:
  aws:region: eu-central-1
  aws:accessKey:
    secure: AAABAKmKGsyb5ViX/YflcQSFJWmX8XRxe55LW0AEPIuPpz8k+WHzbsuSvsT/jxinkOS2+g==
  aws:secretKey:
    secure: AAABAAhblJk+8U5Ze7NJI4yRFqa1JXnCiJNCbzKqIqB2PEKnL/1YrlW/hLZOPF4Fu3blGmSfc5Ssci6YXZBtC57nXGsCHnFS
