config:
  aws:region: eu-central-1
  aws:accessKey:
    secure: AAABAEi5rviIhuagE/VaAODqw+I4Pqt3HzmC77Vh0YK77OWFRr7k6uSAJj9ZZJmBeoEsmQ==
  aws:secretKey:
    secure: AAABANufFO2cjW2rQDzPrmKoiDF4KWRN2VRvjquwFqR6qxwpsF13DAfOuTvaPpiWYVKvhSYCtqgMXyllNSQe36LM2FAdEw3C
